# Generated by Django 4.0.4 on 2022-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=200)),
                ('subject_title', models.CharField(max_length=200)),
                ('date_created', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_schedule', models.CharField(max_length=200)),
                ('time_schedule', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=200)),
                ('seminar_type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('conducted', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Seminar',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subject_handled', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Workshop',
            },
        ),
    ]
