# Generated by Django 4.0.5 on 2022-06-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMSapp', '0003_alter_schedule_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Seminar',
        ),
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Workshop',
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'verbose_name_plural': 'Seminar'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name_plural': 'Workshop'},
        ),
    ]
