# Generated by Django 4.0.5 on 2022-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMSapp', '0004_rename_student_seminar_rename_faculty_workshop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='first_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='last_name',
            new_name='conducted',
        ),
        migrations.AddField(
            model_name='seminar',
            name='date_ended',
            field=models.DateField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='date_started',
            field=models.DateField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='time_duration',
            field=models.TimeField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
