# Generated by Django 4.0.5 on 2022-06-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMSapp', '0005_rename_first_name_seminar_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='time_duration',
        ),
    ]
